CPPFLAGS="--std=c++0x"

all: exercise-9-4 exercise-9-5 exercise-9-14 exercise-9-18 init-reversed exercise-9-19 exercise-9-20 exercise-9-26 exercise-9-27 exercise-9-28 exercise-9-41 exercise-9-47 exercise-9-49 exercise-9-50 exercise-9-51 exercise-9-52

exercise-9-4:
exercise-9-5:
exercise-9-14:
exercise-9-18:
exercise-9-19:
exercise-9-20:
exercise-9-26:
exercise-9-27:
exercise-9-28:
exercise-9-41:
exercise-9-47:
exercise-9-49:
exercise-9-50:
exercise-9-51:
exercise-9-52:
init-reversed:
