CPPFLAGS="-std=c++11"

all: exercise-10-1 exercise-10-3 exercise-10-6 exercise-10-9 exercise-10-11 exercise-10-13 exercise-10-14 exercise-10-15 exercise-10-21 exercise-10-22 exercise-10-27 exercise-10-28 exercise-10-29 exercise-10-30 exercise-10-31 exercise-10-32 exercise-10-34 exercise-10-35 exercise-10-36 exercise-10-37

exercise-10-1:
exercise-10-3:
exercise-10-6:
exercise-10-9:
exercise-10-11:
exercise-10-13:
exercise-10-14:
exercise-10-15:
exercise-10-21:
exercise-10-22:
exercise-10-27:
exercise-10-28:
exercise-10-29:
exercise-10-30:
exercise-10-31:
exercise-10-32:
exercise-10-34:
exercise-10-35:
exercise-10-36:
exercise-10-37:
