CPPFLAGS="--std=c++0x"

all: exercise-11-3 exercise-11-4 exercise-11-7 exercise-11-9 exercise-11-12 exercise-11-23 exercise-11-33

exercise-11-3:
exercise-11-4:
exercise-11-7:
exercise-11-9:
exercise-11-12:
exercise-11-23:
exercise-11-33:
