all: exercise-1-1 exercise-1-2 exercise-1-3
	@echo Exercise 1.1
	./exercise-1-1
	@echo Exercise 1.2
	#./exercise-1-2
	@echo Exercise 1.3
	./exercise-1-3


exercise-1-1:

exercise-1-2:

exercise-1-3:

exercise-1-4:
