CPPFLAGS="--std=c++0x"

all: exercise-14-9 exercise-14-35 exercise-14-36 exercise-14-37 exercise-14-38 exercise-14-39 exercise-14-42 exercise-14-43 exercise-14-44

exercise-14-9: Sales_data.cpp Sales_data.h
	$(CXX) $(CPPFLAGS) -o exercise-14-9 Sales_data.cpp exercise-14-9.cpp

exercise-14-35:
exercise-14-36:
exercise-14-37:
exercise-14-38:
exercise-14-39:
exercise-14-42:
exercise-14-43:
exercise-14-44:
