CPPFLAGS="--std=c++0x"

all: exercise-15-3 exercise-15-6 exercise-15-7 exercise-15-15 exercise-15-20 exercise-15-28 exercise-15-29

exercise-15-3:
exercise-15-6:
exercise-15-7:
exercise-15-15:
exercise-15-20:
exercise-15-28:
exercise-15-29:
