CPPFLAGS?="--std=c++0x"

all: exercise-12-1 exercise-12-6 exercise-12-7 exercise-12-20 run-queries

exercise-12-1: StrBlob.o
exercise-12-6:
exercise-12-7:
exercise-12-20: StrBlob.o
run-queries: TextQuery.o
TextQuery.o:
